# permissions for end users to edit apusicas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apusicas-editor-role
rules:
- apiGroups:
  - webserver.apusic.com
  resources:
  - apusicas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webserver.apusic.com
  resources:
  - apusicas/status
  verbs:
  - get
