# permissions for end users to edit apusiccontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apusiccontrolplane-editor-role
rules:
- apiGroups:
  - webserver.apusic.com
  resources:
  - apusiccontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webserver.apusic.com
  resources:
  - apusiccontrolplanes/status
  verbs:
  - get
